name: Build and deploy to gcloud on pull request to main. Production

on:
  push:
    branches: [ "master", "actions" ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/34272123332/locations/global/workloadIdentityPools/htg-github/providers/htg-repo'
        service_account: "github-docker-connector@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker to use gcloud for authentication
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev -q

    - name: Build Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/htg/htg:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/htg/htg:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy html-to-gomponents \
        --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/htg/htg:latest \
        --region europe-west1 \
        --platform managed \
        --allow-unauthenticated
        
        SERVICE_URL=$(gcloud run services describe html-to-gomponents --platform managed --region europe-west1 --format "value(status.url)")

    - name: Update Repository Description
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        DESCRIPTION="Small tool for development using Gomponents template lib. It allows to convert HTML structures into Gomponents code. Deployed service is available at: $SERVICE_URL"
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }} \
          -d "{\"description\": \"$DESCRIPTION\"}"
