name: Build and deploy to gcloud

on:
  push: 
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      ACTIONS_STEP_DEBUG: true
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/34272123332/locations/global/workloadIdentityPools/htg-github/providers/htg-repo'
        service_account: "github-docker-connector@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker to use gcloud for authentication
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev -q

    - name: Build Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/htg/htg:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/htg/htg:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy your-service-name \
        --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/htg/htg:latest \
        --region europe-west1 \
        --platform managed \
        --allow-unauthenticated
