name: Build and deploy to gcloud

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: 'projects/34272123332/locations/global/workloadIdentityPools/htg-github/providers/htg-repo'
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authenticate Docker with Artifact Registry
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://europe-west1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/htg/htg:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/htg/htg:latest

    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud run deploy your-service-name \
    #     --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/your-repository/your-image:latest \
    #     --region <REGION> \
    #     --platform managed \
    #     --allow-unauthenticated
